#!/usr/bin/env python3
"""Generate the UAS make/model tables from tools/uas_models.json.

Writes firmware/common/uas_models.h (C, header-only) and
app/Sources/Orecchino/UasModels.swift from one source, so the T5's details
card and the Mac app can never disagree about what a serial number means.
`--check` exits non-zero when either generated file is out of date.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "tools" / "uas_models.json"
OUT_C = ROOT / "firmware" / "common" / "uas_models.h"
OUT_SWIFT = ROOT / "app" / "Sources" / "Orecchino" / "UasModels.swift"
BANNER = "GENERATED by tools/gen_uas_models.py from tools/uas_models.json -- edit the JSON, not this file."


def c_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def gen_c(makers: dict, models: dict) -> str:
    out = [
        f"// {BANNER}",
        "// Make and model names for CTA-2063-A serial numbers: the first four",
        "// characters name the maker; DJI's next three name the model. Lookups",
        "// are case-insensitive on the serial. Part of orecchino-esp32.",
        "// SPDX-License-Identifier: GPL-3.0-or-later",
        "#pragma once",
        "",
        "typedef struct { const char* prefix; const char* name; } UasNameEntry;",
        "",
        "static const UasNameEntry UAS_MANUFACTURERS[] = {",
    ]
    out += [f"  {{{c_str(k)}, {c_str(v)}}}," for k, v in sorted(makers.items())]
    out += ["};", f"#define UAS_MANUFACTURERS_N {len(makers)}", "", "static const UasNameEntry UAS_MODELS[] = {"]
    out += [f"  {{{c_str(k)}, {c_str(v)}}}," for k, v in sorted(models.items())]
    out += [
        "};",
        f"#define UAS_MODELS_N {len(models)}",
        "",
        "static inline const char* uas_name_lookup_(const UasNameEntry* t, int n, const char* id, int plen) {",
        "  if (!id) return 0;",
        "  for (int i = 0; i < plen; i++) if (!id[i]) return 0;   // shorter than the prefix",
        "  for (int k = 0; k < n; k++) {",
        "    int i = 0;",
        "    for (; i < plen; i++) {",
        "      char a = id[i];",
        "      if (a >= 'a' && a <= 'z') a = (char)(a - 32);",
        "      if (a != t[k].prefix[i]) break;",
        "    }",
        "    if (i == plen) return t[k].name;",
        "  }",
        "  return 0;",
        "}",
        "/// Maker for a serial-number UAS ID, or NULL when its code is unknown.",
        "static inline const char* uas_manufacturer_name(const char* id) {",
        "  return uas_name_lookup_(UAS_MANUFACTURERS, UAS_MANUFACTURERS_N, id, 4);",
        "}",
        "/// Model for a serial-number UAS ID, or NULL when its prefix is unknown.",
        "static inline const char* uas_model_name(const char* id) {",
        "  return uas_name_lookup_(UAS_MODELS, UAS_MODELS_N, id, 8);",
        "}",
        "",
    ]
    return "\n".join(out)


def gen_swift(makers: dict, models: dict) -> str:
    out = [
        f"// {BANNER}",
        "// Make and model names for CTA-2063-A serial numbers: the first four",
        "// characters name the maker; DJI's next three name the model.",
        "import Foundation",
        "",
        "enum UasModels {",
        "    static let manufacturers: [String: String] = [",
    ]
    out += [f"        {c_str(k)}: {c_str(v)}," for k, v in sorted(makers.items())]
    out += ["    ]", "    static let models: [String: String] = ["]
    out += [f"        {c_str(k)}: {c_str(v)}," for k, v in sorted(models.items())]
    out += [
        "    ]",
        "",
        "    /// Maker for a serial-number UAS ID, when its 4-character code is known.",
        "    static func manufacturer(serial: String) -> String? {",
        "        guard serial.count >= 5 else { return nil }",
        "        return manufacturers[String(serial.prefix(4)).uppercased()]",
        "    }",
        "    /// Model for a serial-number UAS ID, when its 8-character prefix is known.",
        "    static func model(serial: String) -> String? {",
        "        guard serial.count >= 8 else { return nil }",
        "        return models[String(serial.prefix(8)).uppercased()]",
        "    }",
        "}",
        "",
    ]
    return "\n".join(out)


def main() -> int:
    data = json.loads(SRC.read_text(encoding="utf-8"))
    makers, models = data["manufacturers"], data["models"]
    want = {OUT_C: gen_c(makers, models), OUT_SWIFT: gen_swift(makers, models)}
    if "--check" in sys.argv:
        stale = [p for p, text in want.items() if not p.exists() or p.read_text(encoding="utf-8") != text]
        for p in stale:
            print(f"stale: {p.relative_to(ROOT)} (run tools/gen_uas_models.py)")
        print("generated tables are current" if not stale else f"{len(stale)} file(s) out of date")
        return 1 if stale else 0
    for p, text in want.items():
        p.write_text(text, encoding="utf-8")
        print(f"wrote {p.relative_to(ROOT)}: {len(makers)} makers, {len(models)} models")
    return 0


if __name__ == "__main__":
    sys.exit(main())
